# Generated by Django 3.0.3 on 2020-03-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200309_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='auther',
            new_name='author',
        ),
    ]
